# Generated by Django 5.0.3 on 2024-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=None, null=True, upload_to='static/profilepic/', verbose_name='profile pic'),
        ),
    ]
