# Generated by Django 5.0.3 on 2024-03-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Price')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/productimage/', verbose_name='productimage')),
            ],
        ),
    ]
